### ISSUE TITLE
Are the following details correct? 

### ISSUE THREAD

**Issue by prastut** [gnosis/GECO#34]
Hi Gnosis Team!

I am currently investigating how I can contribute to the gnosis ecosystem. I happened to land on the grants page and I was going through the readme where I felt I needed some clarification. Are these following details correct? 

## Question 1
> For this reason, we are offering grants of between $5.000 and $100.000, which will be paid out in GNO tokens.

Is the funding amount correct? 

## Question 2
> https://github.com/gnosis/GECO#roadmap

Is the roadmap correct, seems like first round of submission would be in 2018?

Also I wasn't sure where I can ask questions regarding bounties. Is there a channel where I can raise questions? 

Thank you for your time and consideration :)

**Comment by GnosisEcosystemFund** [comment]
Hey @prastut, 
Great to hear you are interested in applying for the GECO. 
Yes the sums are ok. We are in total giving out $125,000 per Wave. 
For a project you can ask for funding between $5,000-$100,00. 
If you have a look at the teams we are funding already you can get an esitmation off how much funds to ask for a specific project. 
https://blog.gnosis.pm/gnosis-ecosystem-fund-update-i-f64dfd185f33
https://blog.gnosis.pm/gnosis-ecosystem-fund-update-ii-9bea803a97c8

The first submission was end of 2018. We are running different rounds over this year. 
The next submission deadline is on the 30th of June 2019. 

If you have more questions you could go to https://gitter.im/gnosis/GECO?source=orgpage

Best wishes
